In [1]:
import typing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import QuantLib as ql
import yfinance as yf


In [2]:
def foo(df: pd.DataFrame) -> None:
    print(df.iloc[-1])

In [3]:
def retrieve_stock_history(ticker_id: str, auto_adjust: bool, start_date: str, end_date: str) -> pd.DataFrame:
    ticker = yf.Ticker(ticker_id)
    ticker.options
    # opt = ticker.option_chain('2023-11-06')
    # print(opt)
    return ticker.history(auto_adjust = auto_adjust, start = start_date, end = end_date)

In [4]:
print(f"The type of foo is {type(foo)}")

The type of foo is <class 'function'>


In [5]:
START_DATE = '2023-08-09'
END_DATE = '2023-11-06'
lonza = retrieve_stock_history(ticker_id = "LONN.SW", auto_adjust = False, start_date = START_DATE, end_date = END_DATE)
sika = retrieve_stock_history(ticker_id = "SIKA.SW", auto_adjust = False, start_date = START_DATE, end_date = END_DATE)

display(lonza)
display(sika)

Open        High         Low       Close  \
Date                                                                        
2023-08-09 00:00:00+02:00  496.899994  497.500000  488.299988  489.000000   
2023-08-10 00:00:00+02:00  489.100006  504.200012  489.100006  498.100006   
2023-08-11 00:00:00+02:00  495.600006  500.200012  490.700012  494.899994   
2023-08-14 00:00:00+02:00  495.100006  499.399994  493.600006  494.200012   
2023-08-15 00:00:00+02:00  491.000000  493.299988  486.899994  487.899994   
...                               ...         ...         ...         ...   
2023-10-30 00:00:00+01:00  315.799988  317.200012  308.799988  311.500000   
2023-10-31 00:00:00+01:00  310.000000  319.500000  309.399994  316.799988   
2023-11-01 00:00:00+01:00  318.600006  321.600006  313.600006  318.600006   
2023-11-02 00:00:00+01:00  320.000000  326.600006  318.100006  320.000000   
2023-11-03 00:00:00+01:00  322.000000  336.899994  319.500000  329.100006   

                            Adj Close  Volume  Dividends  Stock Splits  
Date                                                                    
2023-08-09 00:00:00+02:00  489.000000   97499        0.0           0.0  
2023-08-10 00:00:00+02:00  498.100006  119920        0.0           0.0  
2023-08-11 00:00:00+02:00  494.899994   91645        0.0           0.0  
2023-08-14 00:00:00+02:00  494.200012   76453        0.0           0.0  
2023-08-15 00:00:00+02:00  487.899994   91655        0.0           0.0  
...                               ...     ...        ...           ...  
2023-10-30 00:00:00+01:00  311.500000  316737        0.0           0.0  
2023-10-31 00:00:00+01:00  316.799988  476956        0.0           0.0  
2023-11-01 00:00:00+01:00  318.600006  316285        0.0           0.0  
2023-11-02 00:00:00+01:00  320.000000  437285        0.0           0.0  
2023-11-03 00:00:00+01:00  329.100006  437078        0.0           0.0  

[63 rows x 8 columns]

Open        High         Low       Close  \
Date                                                                        
2023-08-09 00:00:00+02:00  269.000000  269.600006  265.500000  265.500000   
2023-08-10 00:00:00+02:00  265.899994  269.500000  264.700012  268.299988   
2023-08-11 00:00:00+02:00  266.700012  266.899994  262.100006  262.799988   
2023-08-14 00:00:00+02:00  262.200012  263.000000  259.100006  262.500000   
2023-08-15 00:00:00+02:00  262.200012  262.399994  257.200012  258.100006   
...                               ...         ...         ...         ...   
2023-10-30 00:00:00+01:00  216.699997  217.899994  212.500000  214.100006   
2023-10-31 00:00:00+01:00  214.000000  218.100006  213.500000  216.899994   
2023-11-01 00:00:00+01:00  215.800003  217.399994  213.399994  215.199997   
2023-11-02 00:00:00+01:00  218.600006  227.100006  218.500000  223.800003   
2023-11-03 00:00:00+01:00  225.000000  231.500000  223.800003  227.800003   

                            Adj Close  Volume  Dividends  Stock Splits  
Date                                                                    
2023-08-09 00:00:00+02:00  265.500000  190804        0.0           0.0  
2023-08-10 00:00:00+02:00  268.299988  188447        0.0           0.0  
2023-08-11 00:00:00+02:00  262.799988  158142        0.0           0.0  
2023-08-14 00:00:00+02:00  262.500000  199199        0.0           0.0  
2023-08-15 00:00:00+02:00  258.100006  165529        0.0           0.0  
...                               ...     ...        ...           ...  
2023-10-30 00:00:00+01:00  214.100006  199978        0.0           0.0  
2023-10-31 00:00:00+01:00  216.899994  412760        0.0           0.0  
2023-11-01 00:00:00+01:00  215.199997  296401        0.0           0.0  
2023-11-02 00:00:00+01:00  223.800003  460255        0.0           0.0  
2023-11-03 00:00:00+01:00  227.800003  351616        0.0           0.0  

[63 rows x 8 columns]

In [32]:
lonza_close = lonza[['Adj Close']] # Date is index
sika_close = sika[['Adj Close']]
display(lonza_close)
display(sika_close)

Adj Close
Date                                 
2023-08-09 00:00:00+02:00  489.000000
2023-08-10 00:00:00+02:00  498.100006
2023-08-11 00:00:00+02:00  494.899994
2023-08-14 00:00:00+02:00  494.200012
2023-08-15 00:00:00+02:00  487.899994
...                               ...
2023-10-30 00:00:00+01:00  311.500000
2023-10-31 00:00:00+01:00  316.799988
2023-11-01 00:00:00+01:00  318.600006
2023-11-02 00:00:00+01:00  320.000000
2023-11-03 00:00:00+01:00  329.100006

[63 rows x 1 columns]

Adj Close
Date                                 
2023-08-09 00:00:00+02:00  265.500000
2023-08-10 00:00:00+02:00  268.299988
2023-08-11 00:00:00+02:00  262.799988
2023-08-14 00:00:00+02:00  262.500000
2023-08-15 00:00:00+02:00  258.100006
...                               ...
2023-10-30 00:00:00+01:00  214.100006
2023-10-31 00:00:00+01:00  216.899994
2023-11-01 00:00:00+01:00  215.199997
2023-11-02 00:00:00+01:00  223.800003
2023-11-03 00:00:00+01:00  227.800003

[63 rows x 1 columns]

### Archive

In [7]:
# lonza_ticker = yf.Ticker("LONN.SW") # Lonza Group AG's ticker is LONN.SW
# sika_ticker = yf.Ticker("SIKA.SW") # Sika AG's ticker is SIKA.SW
# # print(f"The type of lonza is {type(lonza)}")
# lonza = lonza_ticker.history(auto_adjust = False, start = '2023-08-01', end = '2023-11-06') # Returns a df, adjust close by default
# sika = sika_ticker.history(period = '1mo', auto_adjust = False, start = '2023-08-01', end = '2023-11-06') # Returns a df

# print(lonza_ticker.options) # No options available
# display(lonza)
# display(sika)
# yf github (download - multiple tickers, history - single ticker): https://github.com/ranaroussi/yfinance/wiki/Ticker
# Auto adjust: https://stackoverflow.com/questions/71731841/different-price-between-yf-download-and-yf-ticker#comment126768818_71731841
# Close is adjusted for split, Adjusted close is the price after accounting for split, dividend distributions
# LONZA.SW historical prices: https://sg.finance.yahoo.com/quote/LONN.SW/history?p=LONN.SW


# TODO: Get business days, account for today, time to maturity T, t, initial fixing date etc.
# TODO: Get options data from BUS lib

In [8]:
# Function of the model should take in a list? Assume multi-asset for multidimensional GBM
pd.to_datetime('2023-11-06')

# Riemann sum: https://brilliant.org/wiki/riemann-sums/#:~:text=A%20Riemann%20sum%20is%20an,value%20of%20the%20area%20exactly.

Timestamp('2023-11-06 00:00:00')

In [48]:
lonza_array = np.array(lonza_close['Adj Close'])
sika_array = np.array(sika_close['Adj Close'])

cov_matrix = np.cov(lonza_array, sika_array)
print(f"Covariance matrix is:\n {cov_matrix}\n")
print(f"The shape is {np.shape(cov_matrix)}\n")

print(f"Correlation between the two var is {cov_matrix[0][1] / (cov_matrix[0][0] * cov_matrix[1][1]) ** 0.5}") # Correct

L = np.linalg.cholesky(cov_matrix)
print(f"The matrix after Cholesky decomposition is:\n {L}\n")

print(f"The multiplication of L and L transpose is:\n {np.dot(L, L.T)}\n") 
# Cannot use *
# Retrieve the original covariance matrix


Covariance matrix is:
 [[3865.74234291  766.60975429]
 [ 766.60975429  190.08057678]]

The shape is (2, 2)

Correlation between the two var is 0.8943119175187743
The matrix after Cholesky decomposition is:
 [[62.17509423  0.        ]
 [12.32985271  6.16889851]]

The multiplication of L and L transpose is:
 [[3865.74234291  766.60975429]
 [ 766.60975429  190.08057678]]



## Covariance matrix

In [16]:
arr_1 = np.array([0, 1, 3, 5])
arr_2 = np.array([1, 2, 8, 5])

cov_matrix = np.cov(arr_1, arr_2)
print(np.shape(cov_matrix))
print(cov_matrix)

()
4.916666666666666


In [25]:
x = np.array([[0, 2], [5, 1], [2, 0]])
# 3 rows, 2 columns
print(x)
print(np.cov(x))
print(np.var(x[0]))
print(np.var(x[0], ddof = 1)) 
# Delta degrees of freedom = 1 for sample variance
# Now the variance matches the diagonal elements in the covariance

[[0 2]
 [5 1]
 [2 0]]
[[ 2. -4. -2.]
 [-4.  8.  4.]
 [-2.  4.  2.]]
1.0
2.0


In [14]:
x = [1.23, 2.12, 3.34, 4.5]  
y = [2.56, 2.89, 3.76, 3.95]  
    
# find out covariance with respect  
# rows  
cov_mat = np.stack((x, y), axis = 1)   

print(cov_mat)

print("shape of matrix x and y:",  
      np.shape(cov_mat))  
  
print("shape of covariance matrix:", 
      np.shape(np.cov(cov_mat)))  
  
print(np.cov(cov_mat))

[[1.23 2.56]
 [2.12 2.89]
 [3.34 3.76]
 [4.5  3.95]]
shape of matrix x and y: (4, 2)
shape of covariance matrix: (4, 4)
[[ 0.88445  0.51205  0.2793  -0.36575]
 [ 0.51205  0.29645  0.1617  -0.21175]
 [ 0.2793   0.1617   0.0882  -0.1155 ]
 [-0.36575 -0.21175 -0.1155   0.15125]]
